export const SET_GENRES_FILMS = 'SET_GENRES_FILMS';
export const SET_ERROR_GENRES_FILMS = 'SET_ERROR_GENRES_FILMS';
export const SET_FILMS_BY_GENRES = 'SET_FILMS_BY_GENRES';
export const RESET_LOADING_FILMS_BY_GENRES = 'RESET_LOADING_FILMS_BY_GENRES';
export const SET_CURRENT_GENRES = 'SET_CURRENT_GENRES';
export const SET_CURRENT_PAGE_FILMS_BY_GENRES = 'SET_CURRENT_PAGE_FILMS_BY_GENRES';
