export const SET_POPULAR_FILMS = 'SET_POPULAR_FILMS';
export const SET_ERROR_POPULAR_FILMS = 'SET_ERROR_POPULAR_FILMS';
export const RESET_FILMS_LOADING = 'RESET_FILMS_LOADING';
export const SET_CURRENT_PAGE_POPULAR_FILMS = 'SET_CURRENT_PAGE';
