export const SET_TOP_RATED_FILMS = 'SET_TOP_RATED_FILMS';
export const SET_ERROR_TOP_RATED_FILMS = 'SET_ERROR_TOP_RATED_FILMS';
export const SET_CURRENT_PAGE_TOP_RATED_FILMS = 'SET_CURRENT_PAGE_TOP_RATED_FILMS';
export const RESET_FILMS_LOADING_TOP_RATED_FILMS = 'RESET_FILMS_LOADING_TOP_RATED_FILMS';
